<?xml version="1.0" encoding="utf-8"?><Database Name="TestingDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-4P3FJHN;Initial Catalog=TestingDatabase;Integrated Security=True" SettingsObjectName="AIUB_CMS.Properties.Settings" SettingsPropertyName="TestingDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LoginTest" Member="LoginTests">
    <Type Name="LoginTest">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RawPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>